resource_group_name = "Grupo_Ruben"
location            = "westeurope"
acr_name            = "ACRRuben"
vm_name             = "MiMaquina"
admin_username      = "adminuser"
ssh_public_key_path = "~/.ssh/id_rsa.pub"
aks_cluster_name    = "AKSRuben"
aks_dns_prefix      = "rubenpio"
client_id           = ""
client_secret       = ""
vnet_name           = "Red1"
subnet_name         = "Subred1"
nic_name            = "Interface1"
ip_pub              = "Mi-ip-pub"

