apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ruben
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: frontend
        image: "acrruben.azurecr.io/aks/wordpress:CasoPractico2"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ruben
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ruben
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "acrruben.azurecr.io/aks/CasoPractico2"
        env:
         - name: ALLOW_EMPTY_PASSWORD
           value: "yes"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ruben
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

