metadata:
  name: "backend"
  namespace: "ruben"
spec:
  ports:
  - port: 6379
  selector:
    app: "backend"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "frontend"
  namespace: "ruben"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend"
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
        - name: "frontend"
          image: acrruben.azurecr.io/unir/caso_practico2/azure-vote-front
          resources:
            request:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 80
          env:
            - name: Pre
              value: "backend"
---
apiVersion: v1
kind: Service
metadata:
  name: "frontend"
  namespace: "ruben"
spec:
  type: LoadBalancer
  selector:
    app: "frontend"
  ports:
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "backend"
  namespace: "ruben"
spec:
  replicas: 1
selector:
    matchLabels:
      app: "backend"
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
        - name: "backend"
          image: acrruben.azurecr.io/unir/caso_practico2/redis
          resources:
            request:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 6379
            - name: redis
          env:
            - name: ALLOW_EMPTY_PASSWORD
            - value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: "backend"
  namespace: "ruben"
spec:
  ports:
   - port: 6379
  selector:
    app: "backend"
