- name: Desplegar aplicaci贸n en AKS con Podman
  hosts: localhost
  gather_facts: no
  vars_files:
   - vars.yaml
  tasks:
    - name: Descargar imagen de la aplicaci贸n desde el registro privado
      containers.podman.podman_image:
        name: "{{ acr_name }}.azurecr.io/caso_practico2/{{ image_name1 }}"
        pull: yes
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

    - name: Desplegar la aplicaci贸n en AKS
      k8s:
        state: present
        definition: ruta_al_archivo_de_despliegue.yaml

    - name: Exponer la aplicaci贸n a Internet
      k8s_service:
        state: present
        definition: ruta_al_archivo_de_servicio.yaml

